### ISSUE TITLE
タイポ

### ISSUE THREAD

**Issue by midorizemi** [johna1203/amazonpay-demoshop#3]
タイポしています．
https://github.com/johna1203/amazonpay-demoshop/blob/ca044b8944b27a555ec8f56c8e45a78385b912ad/sample/shop-confirmation.php#L302
```php
- $amazonCaptureId   = $captureDetail['AmazonCaptureId'];
+ $amazonCaptureId   = $captureDetails['AmazonCaptureId'];
```

**Comment by johna1203** [comment]
おっ！ありがとうございます。
修正します。

**Comment by johna1203** [comment]
https://github.com/johna1203/amazonpay-demoshop/commit/373a48f51c37f5452cc24b34bcd998eef91bbf7b

修正したました。ありがとうございました。
